// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package auth

import (
	"gf-boilerplate/apibackend/auth"
)

type ControllerRole struct{}

func NewRole() auth.IAuthRole {
	return &ControllerRole{}
}

type ControllerMember struct{}

func NewMember() auth.IAuthMember {
	return &ControllerMember{}
}

type ControllerMenu struct{}

func NewMenu() auth.IAuthMenu {
	return &ControllerMenu{}
}

type ControllerAccess struct{}

func NewAccess() auth.IAuthAccess {
	return &ControllerAccess{}
}
