# 本文件采用 MIT 许可证 https://opensource.org/license/mit
# 版权所有 (c) 2021-2025 Marat Reymers

## GolangCI-Lint 黄金配置 v2.0.2
#
# 这是基于作者经验和观点整理的最佳实践配置
# 配置规则较为严格但不过分苛刻
# 建议根据实际项目需求进行调整
# 如果本配置对您有帮助，请保留本文件链接作为参考

# 基于 https://gist.github.com/maratori/47a4d00457a92aa426dbd48a18776322

version: "2"

run: 
  skip-dirs:
    - internal/dao/internal
  skip-files:
    - 

issues:
  max-same-issues: 50

formatters:
  enable:
    - goimports
    - golines
    - gci
  settings:
    goimports:
      local-prefixes:
        - gf-boilerplate
    gci:
      sections:
        - standard 
        - blank 
        - default 
        - dot 
        - prefix(github.com/gogf/gf) 
        - localmodule 

    custom-order: true
    skip-generated: true  
    golines:
      max-len: 120

linters:
  enable:
    - asasalint
    - asciicheck
    - bodyclose
    - cyclop
    - dupl
    - errcheck
    - goconst
    - gocritic
    - gosec
    - prealloc
    - bidichk
    - canonicalheader
    - copyloopvar
    - depguard
    - durationcheck
    - errname
    - errorlint
    - exhaustive
    - fatcontext
    - forbidigo
    - funlen
    - gochecknoinits
    - gocognit
    - govet
    - ineffassign
    - nilnil
    - makezero
    - mirror
    - mnd
    - musttag
    - nakedret
    - nestif
    - noctx
    - perfsprint
    - revive
    - sqlclosecheck
    - staticcheck
    - testpackage
    - unconvert
    - unused
    - wastedassign
    - whitespace

  settings:
    cyclop:
      max-complexity: 30
      package-average: 10.0

    depguard:
      rules:
        "security":
          deny:
            - pkg: "crypto/md5"
              desc: "MD5 不安全，请使用 crypto/sha256"
            - pkg: "crypto/sha1"
              desc: "SHA1 不安全，请使用 crypto/sha256"
        
        "deprecated":
          deny:
            - pkg: github.com/golang/protobuf
              desc: 请使用 google.golang.org/protobuf
            - pkg: github.com/satori/go.uuid
              desc: 请使用 github.com/google/uuid

    errcheck:
      check-type-assertions: true
      check-blank: true

    exhaustive:
      check: [switch, map]

    funlen:
      lines: 100
      statements: 50

    govet:
      enable-all: true
      disable: [fieldalignment]

    mnd:
      ignored-functions:
        - os.Chmod
        - prometheus.ExponentialBuckets.*

    nolintlint:
      require-explanation: true
      require-specific: true

    revive: 
      rules:
        - name: package-comments
          severity: warning
          disabled: true
          exclude: [""]

    staticcheck:
      checks:
        
  exclusions:
    warn-unused: true

    rules:
      - path: '_test\.go'
        linters:
          - bodyclose
          - dupl
    