{
 "title": "wlink",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "整体 RPS (Overall RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "路由 RPS (RPS by Route)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_total[$__rate_interval])) by (http_route)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "平均请求持续时间 ms(Average Request Duration)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_sum[$__rate_interval]))\n/\nsum(rate(http_server_request_duration_count[$__rate_interval]))",
     "legendFormat": "所有请求"
    }
   ]
  },
  {
   "title": " P99 请求持续时间 / P95 请求持续时间",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_request_duration_bucket[$__rate_interval])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_request_duration_bucket[$__rate_interval])) by (le))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "请求输入/输出流量 单位:bytes/sec (B/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_body_size[$__rate_interval]))",
     "legendFormat": "输入流量"
    },
    {
     "expr": "sum(rate(http_server_response_body_size[$__rate_interval]))",
     "legendFormat": "输出流量"
    }
   ]
  },
  {
   "title": "响应输出流量 (Outgoing Response Data Rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(http_server_response_body_size[$__rate_interval])) by (http_route)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "活跃请求数 (Active Requests)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(http_server_request_active) by (http_route)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(http_server_request_active)",
     "legendFormat": "总请求"
    }
   ]
  },
  {
   "title": " 5xx 错误率 (%) / 4xx 错误率 (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_total{http_response_status_code=~\"5..\"}[$__rate_interval]))\n/\nsum(rate(http_server_request_total[$__rate_interval])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GC 暂停时间占总时间百分比 (Time Spent in GC Pause)",
   "type": "timeseries",
   "description": "每秒钟有多少秒用于GC暂停。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(process_runtime_go_gc_pause_total_ns[$__rate_interval]) / 1e9 * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Go 内存使用情况 (Go Memory Usage)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "process_runtime_go_mem_heap_alloc{otel_scope_name=\"go.opentelemetry.io/contrib/instrumentation/runtime\"}",
     "legendFormat": "已分配堆对象"
    },
    {
     "expr": "process_runtime_go_mem_heap_inuse{otel_scope_name=\"go.opentelemetry.io/contrib/instrumentation/runtime\"}",
     "legendFormat": "使用中的堆空间"
    },
    {
     "expr": "process_runtime_go_mem_heap_idle{otel_scope_name=\"go.opentelemetry.io/contrib/instrumentation/runtime\"}",
     "legendFormat": "空闲堆空间"
    },
    {
     "expr": "process_runtime_go_mem_heap_sys{otel_scope_name=\"go.opentelemetry.io/contrib/instrumentation/runtime\"}",
     "legendFormat": "从OS获取的堆内存"
    },
    {
     "expr": "process_runtime_go_mem_heap_released{otel_scope_name=\"go.opentelemetry.io/contrib/instrumentation/runtime\"}",
     "legendFormat": "已释放给OS的堆内存"
    }
   ]
  },
  {
   "title": "GC 发生频率 (GC Cycles Rate) count/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "rate(process_runtime_go_gc_count[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Goroutine 数量 (Goroutine Count)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    { "expr": "process_runtime_go_goroutines", "legendFormat": "__auto" }
   ]
  }
 ]
}