// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gf-boilerplate/internal/dao/internal"
)

// casbinDao is the data access object for the table casbin.
// You can define custom methods on it to extend its functionality as needed.
type casbinDao struct {
	*internal.CasbinDao
}

var (
	// Casbin is a globally accessible object for table casbin operations.
	Casbin = casbinDao{internal.NewCasbinDao()}
)

// Add your custom methods and functionality below.
