// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-boilerplate/internal/dao/internal"
)

// internalGooseDbVersionDao is internal type for wrapping internal DAO implements.
type internalGooseDbVersionDao = *internal.GooseDbVersionDao

// gooseDbVersionDao is the data access object for table goose_db_version.
// You can define custom methods on it to extend its functionality as you wish.
type gooseDbVersionDao struct {
	internalGooseDbVersionDao
}

var (
	// GooseDbVersion is globally public accessible object for table goose_db_version operations.
	GooseDbVersion = gooseDbVersionDao{
		internal.NewGooseDbVersionDao(),
	}
)

// Fill with you ideas below.
