// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gf-boilerplate/internal/dao/internal"
)

// roleMenuMappingDao is the data access object for the table role_menu_mapping.
// You can define custom methods on it to extend its functionality as needed.
type roleMenuMappingDao struct {
	*internal.RoleMenuMappingDao
}

var (
	// RoleMenuMapping is a globally accessible object for table role_menu_mapping operations.
	RoleMenuMapping = roleMenuMappingDao{internal.NewRoleMenuMappingDao()}
)

// Add your custom methods and functionality below.
