// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gf-boilerplate/internal/dao/internal"
)

// superAdminDao is the data access object for the table super_admin.
// You can define custom methods on it to extend its functionality as needed.
type superAdminDao struct {
	*internal.SuperAdminDao
}

var (
	// SuperAdmin is a globally accessible object for table super_admin operations.
	SuperAdmin = superAdminDao{internal.NewSuperAdminDao()}
)

// Add your custom methods and functionality below.
